apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: nginx
