apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.21  # 👈 Updated version for dev
