apiVersion: batch/v1
kind: Job
metadata:
  name: post-hook-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1" # Executes after the deployment
spec:
  template:
    spec:
      containers:
      - name: post-hook
        image: busybox
        command:
          [
            "sh",
            "-c",
            "echo 'Running post-hook...'; sleep 5; echo 'Simulating failure'; exit 1"
          ] # Exit with non-zero status
      restartPolicy: Never
  backoffLimit: 0 # No retries, fail immediately
