apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /index.html
              port: 80
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            failureThreshold: 3
            periodSeconds: 5
